// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB23nbEOmfaPABPD4Bra90UF3WjjJ1IJpc',
    appId: '1:866835284470:web:b1ef0a1126efffb59f47d7',
    messagingSenderId: '866835284470',
    projectId: 'rentcar-3c3f1',
    authDomain: 'rentcar-3c3f1.firebaseapp.com',
    storageBucket: 'rentcar-3c3f1.appspot.com',
    measurementId: 'G-FXCMN027NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0eEdigyl5ife2aClEk5OgU7dTpj4ETUM',
    appId: '1:866835284470:android:88ca3294169805ca9f47d7',
    messagingSenderId: '866835284470',
    projectId: 'rentcar-3c3f1',
    storageBucket: 'rentcar-3c3f1.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB23nbEOmfaPABPD4Bra90UF3WjjJ1IJpc',
    appId: '1:866835284470:web:197fcc04d25a9c679f47d7',
    messagingSenderId: '866835284470',
    projectId: 'rentcar-3c3f1',
    authDomain: 'rentcar-3c3f1.firebaseapp.com',
    storageBucket: 'rentcar-3c3f1.appspot.com',
    measurementId: 'G-62758PWDZP',
  );
}
